spring:
  datasource:
    password: passdb
    url: jdbc:postgresql://db:5432/testdb
    username: testuser
  application:
    name: techtest-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: Accept,Content-Type,credentials,Content-Length,Accept-Encoding,Authorization